# -*- coding: utf-8 -*-
"""Copy of versi 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgy4aoPQKltTo61IGO_auTMuEKNgksEg
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import plotly.graph_objects as go
# from datetime import datetime
# 
# # --- KONFIGURASI TANGGAL ---
# bulan_indo = {
#     1: "Januari", 2: "Februari", 3: "Maret", 4: "April", 5: "Mei", 6: "Juni",
#     7: "Juli", 8: "Agustus", 9: "September", 10: "Oktober", 11: "November", 12: "Desember"
# }
# tgl_sekarang = datetime.now()
# hari_ini = f"{tgl_sekarang.day} {bulan_indo[tgl_sekarang.month]} {tgl_sekarang.year}"
# 
# st.set_page_config(page_title=f"Dashboard RM {hari_ini}", layout="wide")
# 
# # --- JUDUL ---
# st.markdown(f"<h1 style='text-align: center;'>📊 KPI RM Private Dashboard</h1>", unsafe_allow_html=True)
# st.markdown(f"<p style='text-align: center;'>Data Terupdate per: <b>{hari_ini}</b></p>", unsafe_allow_html=True)
# st.divider()
# 
# # --- KONEKSI DATA (GOOGLE SHEETS) ---
# # Ganti URL di bawah ini dengan URL Google Sheets Anda yang sudah di-share 'Anyone with link'
# SHEET_URL = "https://docs.google.com/spreadsheets/d/1NNscD0S97ot1ZSurAx8VFsaHy8qBG62L7eVhdRAvUVQ/edit?usp=sharing"
# 
# # Fungsi untuk membaca data
# @st.cache_data(ttl=600) # Data disimpan di cache selama 10 menit
# def load_data(url):
#     # Mengubah URL sharing menjadi URL export CSV
#     csv_url = url.replace('/edit?usp=sharing', '/export?format=csv')
#     return pd.read_csv(csv_url)
# 
# try:
#     df_raw = load_data(SHEET_URL)
# 
#     # --- LOGIKA PERHITUNGAN (Integer/Bulat) ---
#     df = df_raw.copy()
#     num_cols = ["FBI Investasi", "FBI Asuransi", "Ekspansi Tabungan", "AUM Exc Tabungan", "NCG", "PR Deposito", "PR Tapenas"]
# 
#     for col in num_cols:
#         df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).round(0).astype(int)
# 
#     df['KPI Utama'] = ((df["FBI Investasi"] + df["FBI Asuransi"] + df["Ekspansi Tabungan"] + df["AUM Exc Tabungan"] + df["NCG"]) / 5).round(0).astype(int)
#     df['Total Poin Reward Inti'] = (df["PR Deposito"] + df["PR Tapenas"]).clip(upper=30).round(0).astype(int)
#     df['Grand Total'] = (df['KPI Utama'] + df['Total Poin Reward Inti']).round(0).astype(int)
#     df['Status'] = df['Grand Total'].apply(lambda x: "Achieve ✅" if x >= 100 else "Not Achieve ❌")
# 
#     # --- VISUALISASI ---
#     m1, m2, m3 = st.columns(3)
#     m1.metric("Total RM", len(df))
#     m2.metric("Achieve", len(df[df['Status'] == "Achieve ✅"]))
#     m3.metric("Avg Score", f"{int(df['Grand Total'].mean())}%")
# 
#     # Bar Chart Utama
#     fig_main = px.bar(df, x="Nama Sales", y="Grand Total", color="Status",
#                       text="Grand Total", title="Peringkat Performa RM",
#                       color_discrete_map={"Achieve ✅": "#2ecc71", "Not Achieve ❌": "#e74c3c"})
#     fig_main.add_hline(y=100, line_dash="dash", line_color="orange")
#     st.plotly_chart(fig_main, use_container_width=True)
# 
#     # Radar Chart Interaktif
#     st.divider()
#     col_left, col_right = st.columns([1, 2])
# 
#     with col_left:
#         selected_rm = st.selectbox("Pilih RM untuk Detail:", df["Nama Sales"].unique())
#         rm_data = df[df["Nama Sales"] == selected_rm].iloc[0]
# 
#         st.write(f"**Status: {rm_data['Status']}**")
#         st.write(f"KPI Utama: {rm_data['KPI Utama']}%")
#         st.write(f"Poin Reward: {rm_data['Total Poin Reward Inti']}%")
# 
#     with col_right:
#         categories = ["FBI Investasi", "FBI Asuransi", "Ekspansi Tabungan", "AUM Exc Tabungan", "NCG"]
#         fig_radar = go.Figure(data=[go.Scatterpolar(
#             r=[rm_data[c] for c in categories],
#             theta=categories,
#             fill='toself',
#             line_color='#264653'
#         )])
#         fig_radar.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 120])), showlegend=False)
#         st.plotly_chart(fig_radar, use_container_width=True)
# 
# except Exception as e:
#     st.error("Gagal terhubung ke Google Sheets. Pastikan URL benar dan akses sudah 'Anyone with the link'.")
